# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mapdata/GetIntersectionRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetIntersectionRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "mapdata/GetIntersectionRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetIntersectionRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mapdata/GetIntersectionResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mapdata.msg

class GetIntersectionResponse(genpy.Message):
  _md5sum = "05e0de0c4f7d86e84748f13d311cd03e"
  _type = "mapdata/GetIntersectionResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# For our purposes a 4-way intersection is enough
RoadSection north
RoadSection west
RoadSection south
RoadSection east

================================================================================
MSG: mapdata/RoadSection
# If you're standing on the road looking towards the intersection, the left
# position is the leftmost edge of the rectangle closest to the intersection.
#    |       |
#    |       |
#  right    left
# ---+       +----
#
Position left
Position right

# How far the road section extends from the intersection
int32 length

# How far from the intersection the cars should stop
int32 stopline_offset

# Enumeration (just constants) of priority signs
uint8 PRIORITY_ROAD=0
uint8 GIVE_WAY=1
uint8 STOP_SIGN=2
uint8 TRAFFIC_LIGHT=3
uint8 BOOKING=4

uint8 priority_sign

# A bit redundant but nice for pretty printing
string name

================================================================================
MSG: mapdata/Position
int32 x
int32 y
"""
  __slots__ = ['north','west','south','east']
  _slot_types = ['mapdata/RoadSection','mapdata/RoadSection','mapdata/RoadSection','mapdata/RoadSection']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       north,west,south,east

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetIntersectionResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.north is None:
        self.north = mapdata.msg.RoadSection()
      if self.west is None:
        self.west = mapdata.msg.RoadSection()
      if self.south is None:
        self.south = mapdata.msg.RoadSection()
      if self.east is None:
        self.east = mapdata.msg.RoadSection()
    else:
      self.north = mapdata.msg.RoadSection()
      self.west = mapdata.msg.RoadSection()
      self.south = mapdata.msg.RoadSection()
      self.east = mapdata.msg.RoadSection()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6iB().pack(_x.north.left.x, _x.north.left.y, _x.north.right.x, _x.north.right.y, _x.north.length, _x.north.stopline_offset, _x.north.priority_sign))
      _x = self.north.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6iB().pack(_x.west.left.x, _x.west.left.y, _x.west.right.x, _x.west.right.y, _x.west.length, _x.west.stopline_offset, _x.west.priority_sign))
      _x = self.west.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6iB().pack(_x.south.left.x, _x.south.left.y, _x.south.right.x, _x.south.right.y, _x.south.length, _x.south.stopline_offset, _x.south.priority_sign))
      _x = self.south.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6iB().pack(_x.east.left.x, _x.east.left.y, _x.east.right.x, _x.east.right.y, _x.east.length, _x.east.stopline_offset, _x.east.priority_sign))
      _x = self.east.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.north is None:
        self.north = mapdata.msg.RoadSection()
      if self.west is None:
        self.west = mapdata.msg.RoadSection()
      if self.south is None:
        self.south = mapdata.msg.RoadSection()
      if self.east is None:
        self.east = mapdata.msg.RoadSection()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.north.left.x, _x.north.left.y, _x.north.right.x, _x.north.right.y, _x.north.length, _x.north.stopline_offset, _x.north.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.north.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.north.name = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.west.left.x, _x.west.left.y, _x.west.right.x, _x.west.right.y, _x.west.length, _x.west.stopline_offset, _x.west.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.west.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.west.name = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.south.left.x, _x.south.left.y, _x.south.right.x, _x.south.right.y, _x.south.length, _x.south.stopline_offset, _x.south.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.south.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.south.name = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.east.left.x, _x.east.left.y, _x.east.right.x, _x.east.right.y, _x.east.length, _x.east.stopline_offset, _x.east.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.east.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.east.name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6iB().pack(_x.north.left.x, _x.north.left.y, _x.north.right.x, _x.north.right.y, _x.north.length, _x.north.stopline_offset, _x.north.priority_sign))
      _x = self.north.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6iB().pack(_x.west.left.x, _x.west.left.y, _x.west.right.x, _x.west.right.y, _x.west.length, _x.west.stopline_offset, _x.west.priority_sign))
      _x = self.west.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6iB().pack(_x.south.left.x, _x.south.left.y, _x.south.right.x, _x.south.right.y, _x.south.length, _x.south.stopline_offset, _x.south.priority_sign))
      _x = self.south.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6iB().pack(_x.east.left.x, _x.east.left.y, _x.east.right.x, _x.east.right.y, _x.east.length, _x.east.stopline_offset, _x.east.priority_sign))
      _x = self.east.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.north is None:
        self.north = mapdata.msg.RoadSection()
      if self.west is None:
        self.west = mapdata.msg.RoadSection()
      if self.south is None:
        self.south = mapdata.msg.RoadSection()
      if self.east is None:
        self.east = mapdata.msg.RoadSection()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.north.left.x, _x.north.left.y, _x.north.right.x, _x.north.right.y, _x.north.length, _x.north.stopline_offset, _x.north.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.north.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.north.name = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.west.left.x, _x.west.left.y, _x.west.right.x, _x.west.right.y, _x.west.length, _x.west.stopline_offset, _x.west.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.west.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.west.name = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.south.left.x, _x.south.left.y, _x.south.right.x, _x.south.right.y, _x.south.length, _x.south.stopline_offset, _x.south.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.south.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.south.name = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.east.left.x, _x.east.left.y, _x.east.right.x, _x.east.right.y, _x.east.length, _x.east.stopline_offset, _x.east.priority_sign,) = _get_struct_6iB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.east.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.east.name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6iB = None
def _get_struct_6iB():
    global _struct_6iB
    if _struct_6iB is None:
        _struct_6iB = struct.Struct("<6iB")
    return _struct_6iB
class GetIntersection(object):
  _type          = 'mapdata/GetIntersection'
  _md5sum = '05e0de0c4f7d86e84748f13d311cd03e'
  _request_class  = GetIntersectionRequest
  _response_class = GetIntersectionResponse
