// Generated by gencpp from file gv_client/GulliViewPosition.msg
// DO NOT EDIT!


#ifndef GV_CLIENT_MESSAGE_GULLIVIEWPOSITION_H
#define GV_CLIENT_MESSAGE_GULLIVIEWPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gv_client
{
template <class ContainerAllocator>
struct GulliViewPosition_
{
  typedef GulliViewPosition_<ContainerAllocator> Type;

  GulliViewPosition_()
    : header()
    , x(0)
    , y(0)
    , theta(0.0)
    , speed(0.0)
    , tagId(0)
    , cameraId(0)  {
    }
  GulliViewPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0)
    , y(0)
    , theta(0.0)
    , speed(0.0)
    , tagId(0)
    , cameraId(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _speed_type;
  _speed_type speed;

   typedef int32_t _tagId_type;
  _tagId_type tagId;

   typedef int32_t _cameraId_type;
  _cameraId_type cameraId;





  typedef boost::shared_ptr< ::gv_client::GulliViewPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gv_client::GulliViewPosition_<ContainerAllocator> const> ConstPtr;

}; // struct GulliViewPosition_

typedef ::gv_client::GulliViewPosition_<std::allocator<void> > GulliViewPosition;

typedef boost::shared_ptr< ::gv_client::GulliViewPosition > GulliViewPositionPtr;
typedef boost::shared_ptr< ::gv_client::GulliViewPosition const> GulliViewPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gv_client::GulliViewPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gv_client::GulliViewPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gv_client::GulliViewPosition_<ContainerAllocator1> & lhs, const ::gv_client::GulliViewPosition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.speed == rhs.speed &&
    lhs.tagId == rhs.tagId &&
    lhs.cameraId == rhs.cameraId;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gv_client::GulliViewPosition_<ContainerAllocator1> & lhs, const ::gv_client::GulliViewPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gv_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gv_client::GulliViewPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gv_client::GulliViewPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gv_client::GulliViewPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gv_client::GulliViewPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gv_client::GulliViewPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gv_client::GulliViewPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gv_client::GulliViewPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "422884b87830ecb9e6166854972efe25";
  }

  static const char* value(const ::gv_client::GulliViewPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x422884b87830ecb9ULL;
  static const uint64_t static_value2 = 0xe6166854972efe25ULL;
};

template<class ContainerAllocator>
struct DataType< ::gv_client::GulliViewPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gv_client/GulliViewPosition";
  }

  static const char* value(const ::gv_client::GulliViewPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gv_client::GulliViewPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 x\n"
"int32 y\n"
"float32 theta\n"
"float32 speed\n"
"int32 tagId\n"
"int32 cameraId\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gv_client::GulliViewPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gv_client::GulliViewPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.speed);
      stream.next(m.tagId);
      stream.next(m.cameraId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GulliViewPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gv_client::GulliViewPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gv_client::GulliViewPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "tagId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tagId);
    s << indent << "cameraId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cameraId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GV_CLIENT_MESSAGE_GULLIVIEWPOSITION_H
