// Generated by gencpp from file mapdata/GetIntersection.msg
// DO NOT EDIT!


#ifndef MAPDATA_MESSAGE_GETINTERSECTION_H
#define MAPDATA_MESSAGE_GETINTERSECTION_H

#include <ros/service_traits.h>


#include <mapdata/GetIntersectionRequest.h>
#include <mapdata/GetIntersectionResponse.h>


namespace mapdata
{

struct GetIntersection
{

typedef GetIntersectionRequest Request;
typedef GetIntersectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIntersection
} // namespace mapdata


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mapdata::GetIntersection > {
  static const char* value()
  {
    return "05e0de0c4f7d86e84748f13d311cd03e";
  }

  static const char* value(const ::mapdata::GetIntersection&) { return value(); }
};

template<>
struct DataType< ::mapdata::GetIntersection > {
  static const char* value()
  {
    return "mapdata/GetIntersection";
  }

  static const char* value(const ::mapdata::GetIntersection&) { return value(); }
};


// service_traits::MD5Sum< ::mapdata::GetIntersectionRequest> should match
// service_traits::MD5Sum< ::mapdata::GetIntersection >
template<>
struct MD5Sum< ::mapdata::GetIntersectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mapdata::GetIntersection >::value();
  }
  static const char* value(const ::mapdata::GetIntersectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapdata::GetIntersectionRequest> should match
// service_traits::DataType< ::mapdata::GetIntersection >
template<>
struct DataType< ::mapdata::GetIntersectionRequest>
{
  static const char* value()
  {
    return DataType< ::mapdata::GetIntersection >::value();
  }
  static const char* value(const ::mapdata::GetIntersectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mapdata::GetIntersectionResponse> should match
// service_traits::MD5Sum< ::mapdata::GetIntersection >
template<>
struct MD5Sum< ::mapdata::GetIntersectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mapdata::GetIntersection >::value();
  }
  static const char* value(const ::mapdata::GetIntersectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mapdata::GetIntersectionResponse> should match
// service_traits::DataType< ::mapdata::GetIntersection >
template<>
struct DataType< ::mapdata::GetIntersectionResponse>
{
  static const char* value()
  {
    return DataType< ::mapdata::GetIntersection >::value();
  }
  static const char* value(const ::mapdata::GetIntersectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAPDATA_MESSAGE_GETINTERSECTION_H
