// Generated by gencpp from file gv_client/LaptopSpeed.msg
// DO NOT EDIT!


#ifndef GV_CLIENT_MESSAGE_LAPTOPSPEED_H
#define GV_CLIENT_MESSAGE_LAPTOPSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gv_client
{
template <class ContainerAllocator>
struct LaptopSpeed_
{
  typedef LaptopSpeed_<ContainerAllocator> Type;

  LaptopSpeed_()
    : header()
    , tag_id(0)
    , speed(0.0)
    , restart(false)  {
    }
  LaptopSpeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tag_id(0)
    , speed(0.0)
    , restart(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _tag_id_type;
  _tag_id_type tag_id;

   typedef float _speed_type;
  _speed_type speed;

   typedef uint8_t _restart_type;
  _restart_type restart;





  typedef boost::shared_ptr< ::gv_client::LaptopSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gv_client::LaptopSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct LaptopSpeed_

typedef ::gv_client::LaptopSpeed_<std::allocator<void> > LaptopSpeed;

typedef boost::shared_ptr< ::gv_client::LaptopSpeed > LaptopSpeedPtr;
typedef boost::shared_ptr< ::gv_client::LaptopSpeed const> LaptopSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gv_client::LaptopSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gv_client::LaptopSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gv_client::LaptopSpeed_<ContainerAllocator1> & lhs, const ::gv_client::LaptopSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tag_id == rhs.tag_id &&
    lhs.speed == rhs.speed &&
    lhs.restart == rhs.restart;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gv_client::LaptopSpeed_<ContainerAllocator1> & lhs, const ::gv_client::LaptopSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gv_client

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gv_client::LaptopSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gv_client::LaptopSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gv_client::LaptopSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gv_client::LaptopSpeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gv_client::LaptopSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gv_client::LaptopSpeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gv_client::LaptopSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06654cff71f2995da6a11eca73ad520d";
  }

  static const char* value(const ::gv_client::LaptopSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06654cff71f2995dULL;
  static const uint64_t static_value2 = 0xa6a11eca73ad520dULL;
};

template<class ContainerAllocator>
struct DataType< ::gv_client::LaptopSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gv_client/LaptopSpeed";
  }

  static const char* value(const ::gv_client::LaptopSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gv_client::LaptopSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 tag_id\n"
"float32 speed\n"
"bool restart\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gv_client::LaptopSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gv_client::LaptopSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tag_id);
      stream.next(m.speed);
      stream.next(m.restart);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaptopSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gv_client::LaptopSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gv_client::LaptopSpeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tag_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tag_id);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "restart: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.restart);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GV_CLIENT_MESSAGE_LAPTOPSPEED_H
